// 商品数据(JSON格式) - 独立分离，共12个商品，完整保留所有属性
const productData = [
    {
        id: 1001,
        name: "小米14 旗舰智能手机",
        intro: "高清大屏，超长续航",
        price: 2999,
        stock: 500,
        categoryId: 1,
        categoryName: "数码产品",
        imgName: "product1.png",
        features: "骁龙8 Gen3 | 徕卡光学镜头 | 1.5K OLED直屏",
        origin: "中国大陆",
        color: "黑色/白色/青色",
        spec: "12GB+256GB/12GB+512GB",
        size: "6.36英寸",
        shelfDate: "2023-10-26"
    },
    {
        id: 1002,
        name: "华为MatePad 11.5英寸平板",
        intro: "柔光版，学习办公首选",
        price: 2499,
        stock: 350,
        categoryId: 1,
        categoryName: "数码产品",
        imgName: "product2.png",
        features: "麒麟芯片 | 144Hz高刷屏 | 鸿蒙OS",
        origin: "中国大陆",
        color: "深空灰/雪域白",
        spec: "8GB+256GB/8GB+512GB",
        size: "11.5英寸",
        shelfDate: "2024-02-28"
    },
    {
        id: 1003,
        name: "苹果AirPods Pro 第二代",
        intro: "主动降噪，空间音频",
        price: 1799,
        stock: 420,
        categoryId: 1,
        categoryName: "数码产品",
        imgName: "product3.png",
        features: "USB-C接口 | 自适应通透模式 | 防水",
        origin: "越南",
        color: "白色",
        spec: "标准版",
        size: "入耳式",
        shelfDate: "2023-09-22"
    },
    {
        id: 1004,
        name: "罗技K845机械键盘",
        intro: "青轴手感，办公游戏两用",
        price: 299,
        stock: 600,
        categoryId: 1,
        categoryName: "数码产品",
        imgName: "product4.png",
        features: "全尺寸 | 背光 | 可拆卸键帽",
        origin: "中国台湾",
        color: "黑色/白色",
        spec: "青轴/红轴/茶轴",
        size: "442×135×34mm",
        shelfDate: "2022-05-15"
    },
    {
        id: 2001,
        name: "耐克Air Max 休闲运动鞋",
        intro: "透气舒适，防滑耐磨",
        price: 799,
        stock: 280,
        categoryId: 2,
        categoryName: "服装鞋帽",
        imgName: "product5.png",
        features: "气垫缓震 | 网面透气 | 橡胶大底",
        origin: "越南",
        color: "黑色/白色/红色",
        spec: "男女款",
        size: "36-45码",
        shelfDate: "2024-01-10"
    },
    {
        id: 2002,
        name: "优衣库纯棉长袖T恤",
        intro: "舒适亲肤，百搭款",
        price: 99,
        stock: 800,
        categoryId: 2,
        categoryName: "服装鞋帽",
        imgName: "product6.png",
        features: "100%纯棉 | 不易变形 | 多色可选",
        origin: "中国江苏",
        color: "白色/黑色/灰色/蓝色",
        spec: "常规款",
        size: "S/M/L/XL/XXL",
        shelfDate: "2024-03-01"
    },
    {
        id: 2003,
        name: "李宁运动外套",
        intro: "防风防水，轻便保暖",
        price: 399,
        stock: 320,
        categoryId: 2,
        categoryName: "服装鞋帽",
        imgName: "product7.png",
        features: "连帽设计 | 拉链口袋 | 弹力面料",
        origin: "中国福建",
        color: "黑色/蓝色/灰色",
        spec: "常规款/加绒款",
        size: "M/L/XL/XXL",
        shelfDate: "2023-11-18"
    },
    {
        id: 2004,
        name: "百丽真皮商务皮鞋",
        intro: "正装必备，舒适不磨脚",
        price: 599,
        stock: 180,
        categoryId: 2,
        categoryName: "服装鞋帽",
        imgName: "product8.png",
        features: "头层牛皮 | 防滑鞋底 | 透气内里",
        origin: "中国广东",
        color: "黑色/棕色",
        spec: "正装款",
        size: "38-44码",
        shelfDate: "2024-01-25"
    },
    {
        id: 3001,
        name: "美的智能电饭煲",
        intro: "多功能，大容量",
        price: 399,
        stock: 250,
        categoryId: 3,
        categoryName: "家居用品",
        imgName: "product9.png",
        features: "IH加热 | 预约功能 | 5L大容量",
        origin: "中国广东",
        color: "白色",
        spec: "5L",
        size: "380×280×260mm",
        shelfDate: "2023-12-05"
    },
    {
        id: 3002,
        name: "苏泊尔不粘锅炒锅",
        intro: "少油烟，易清洗",
        price: 199,
        stock: 400,
        categoryId: 3,
        categoryName: "家居用品",
        imgName: "product10.png",
        features: "不粘涂层 | 电磁炉通用 | 防烫手柄",
        origin: "中国浙江",
        color: "黑色",
        spec: "32cm",
        size: "32×10cm",
        shelfDate: "2024-02-12"
    },
    {
        id: 4001,
        name: "欧莱雅保湿面霜",
        intro: "补水保湿，提亮肤色",
        price: 129,
        stock: 550,
        categoryId: 4,
        categoryName: "美妆护肤",
        imgName: "product11.png",
        features: "玻尿酸 | 维生素C | 无香精",
        origin: "法国",
        color: "乳白色",
        spec: "50ml",
        size: "50ml",
        shelfDate: "2023-08-15"
    },
    {
        id: 4002,
        name: "雅诗兰黛小棕瓶精华",
        intro: "修护抗老，夜间修复",
        price: 899,
        stock: 150,
        categoryId: 4,
        categoryName: "美妆护肤",
        imgName: "product12.png",
        features: "二裂酵母 | 抗氧化 | 提亮紧致",
        origin: "美国",
        color: "棕色",
        spec: "100ml",
        size: "100ml",
        shelfDate: "2023-10-01"
    }
];